"""Add cascade delete relationships

Revision ID: 1a31ce608336
Revises: d98dd8ec85a3
Create Date: 2024-07-31 22:24:34.447891

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1a31ce608336'
down_revision = 'd98dd8ec85a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('team_owner_id_fkey', 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'users', ['owner_id'], ['user_id'], ondelete='CASCADE')

    op.drop_constraint('user_team_user_id_fkey', 'user_team', type_='foreignkey')
    op.create_foreign_key(None, 'user_team', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    op.drop_constraint('user_team_team_id_fkey', 'user_team', type_='foreignkey')
    op.create_foreign_key(None, 'user_team', 'teams', ['team_id'], ['team_id'], ondelete='CASCADE')

    op.drop_constraint('labs_owner_id_fkey', 'labs', type_='foreignkey')
    op.create_foreign_key(None, 'labs', 'users', ['owner_id'], ['user_id'], ondelete='CASCADE')

    op.drop_constraint('labs_team_id_fkey', 'labs', type_='foreignkey')
    op.create_foreign_key(None, 'labs', 'teams', ['team_id'], ['team_id'], ondelete='CASCADE')

    op.drop_constraint('items_team_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'teams', ['team_id'], ['team_id'], ondelete='CASCADE')

    op.drop_constraint('user_items_user_id_fkey', 'user_items', type_='foreignkey')
    op.create_foreign_key(None, 'user_items', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    op.drop_constraint('user_items_item_id_fkey', 'user_items', type_='foreignkey')
    op.create_foreign_key(None, 'user_items', 'items', ['item_id'], ['item_id'], ondelete='CASCADE')

    op.drop_constraint('user_items_lab_id_fkey', 'user_items', type_='foreignkey')
    op.create_foreign_key(None, 'user_items', 'labs', ['lab_id'], ['lab_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_items', type_='foreignkey')
    op.create_foreign_key('user_items_lab_id_fkey', 'user_items', 'labs', ['lab_id'], ['lab_id'])

    op.drop_constraint(None, 'user_items', type_='foreignkey')
    op.create_foreign_key('user_items_item_id_fkey', 'user_items', 'items', ['item_id'], ['item_id'])

    op.drop_constraint(None, 'user_items', type_='foreignkey')
    op.create_foreign_key('user_items_user_id_fkey', 'user_items', 'users', ['user_id'], ['user_id'])

    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_team_id_fkey', 'items', 'teams', ['team_id'], ['team_id'])

    op.drop_constraint(None, 'labs', type_='foreignkey')
    op.create_foreign_key('labs_team_id_fkey', 'labs', 'teams', ['team_id'], ['team_id'])

    op.drop_constraint(None, 'labs', type_='foreignkey')
    op.create_foreign_key('labs_owner_id_fkey', 'labs', 'users', ['owner_id'], ['user_id'])

    op.drop_constraint(None, 'user_team', type_='foreignkey')
    op.create_foreign_key('user_team_team_id_fkey', 'user_team', 'teams', ['team_id'], ['team_id'])

    op.drop_constraint(None, 'user_team', type_='foreignkey')
    op.create_foreign_key('user_team_user_id_fkey', 'user_team', 'users', ['user_id'], ['user_id'])

    op.drop_constraint(None, 'team', type_='foreignkey')
    op.create_foreign_key('team_owner_id_fkey', 'teams', 'users', ['owner_id'], ['user_id'])
    # ### end Alembic commands ###